---
# ansible-playbook create_ports.yml
- name: create configlets from CSV data
  hosts: localhost

  tasks:

  - name: Read in CSV file
    read_csv:
      path: datafiles/network_ports.csv
    register: network_ports

  - name: Create configlet
    template: src=templates/connected-endpoints.j2 dest=output/endpoints.yml