---
# ansible-playbook create_ports.yml
# Playbook and Template to create connected endpoints to be used in AVD

- name: Create Connected Endpoints
  hosts: localhost

  tasks:

  - name: Read Network Ports from CSV file
    read_csv:
      path: datafiles/connected_endpoints.csv
    register: connected_endpoints

  - name: Generate YML Data Model
    template: src=templates/connected-endpoints.j2 dest=output/endpoints.yml
